wordpress:
  image: wordpress:latest
  ports:
    - "80:80"
  volumes:
    - ./themes/:/var/www/html/wp-content/themes/
    - ./plugins/:/var/www/html/wp-content/plugins/
    - ./uploads/:/var/www/html/wp-content/uploads/
    - ./health.html:/var/www/html/health.html
    - ./hotsites/totvs/:/var/www/html/totvs/
  restart: always
  environment:
    - WORDPRESS_DB_HOST=DB_HOST
    - WORDPRESS_DB_USER=DB_USER
    - WORDPRESS_DB_NAME=DB_NAME
    - WORDPRESS_DB_PASSWORD=DB_PASSWORD
    - WORDPRESS_TABLE_PREFIX=TABLE_PREFIX
